### ISSUE TITLE
Doesn't seem to work?

### ISSUE THREAD

**Issue by BetaKors** [DaFuqs/FluidVoidFading#1]
Hi, I just tried using the mod but the game simply doesn't launch.

I'm using Cloth Config 9.0.94 (latest version) and Fabric API 0.73.0, and no other mods.

The crash report has the following:
```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fluidvoidfading'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchFieldError: field_11154
	at de.dafuqs.fluidvoidfading.FluidVoidFadingClient.onInitializeClient(FluidVoidFadingClient.java:27)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
```

**Comment by DaFuqs** [comment]
Oops. I accidentally flagged the 1.19.2 release as 1.19.3, too. I've now uploaded a working 1.19.3 build. Thanks a lot for the issue report!
