### ISSUE TITLE
Crash with Sodium 0.5.0

### ISSUE THREAD

**Issue by Auzathoth** [DaFuqs/FluidVoidFading#6]
Minecraft 1.20.1 crashes when entering a world - either single or multi-player - when both FVF and the latest version of Sodium are installed. Without Sodium, there's no crash.

Mods: Fluid Void Falling 1.1.0, Fabric API 0.86.1, Cloth Config 11.1.106 and Sodium 0.5.0.

```
Time: 2023-08-05 15:09:46
Description: Unexpected error

java.lang.NullPointerException: Cannot read field "field_44912" because "this.field_4015.field_1724" is null
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```
[crash-2023-08-05_15.09.46-client.txt](https://github.com/DaFuqs/FluidVoidFading/files/12267451/crash-2023-08-05_15.09.46-client.txt)

**Comment by DaFuqs** [comment]
Done.
